Git implicitly required by Sphinx
Error was:
```
Exception occurred:
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git log -1 --format=%cd '--date=short' 2>/dev/null' returned non-zero exit status 127.
The full traceback has been saved in /tmp/sphinx-err-6y_ehwe4.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[1]: Leaving directory '/builds/brobox/appliance-doc/brobox'
make[1]: *** [../common.mk:48: common_latex] Error 1
make: *** [Makefile:30: pdf_brobox] Error 2
ERROR: Job failed: exit code 1
```